apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-as-code-scheduler
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: pipelines-as-code

